import { Router } from "express";
import authRouter from "./authRoutes";
import tenantRouter from "./tenantRoutes";
import geoRouter from "./regionRoutes";
import geoRouterDepartement from "./departementRoutes";
import geoRouterSecteur from "./secteurRoutes";
import geoRouterVillage from "./villageRoutes";
import inviteRouter from "./inviteRoutes";
const router = Router();

// router.use("/auth", authRouter);
// router.use("/tenant", tenantRouter);
// router.use("/geo", geoRouter);
// router.use("/invite", inviteRouter);
router.use("/", authRouter);
router.use("/", tenantRouter);
router.use("/", geoRouter);
router.use("/", geoRouterDepartement);
router.use("/", geoRouterSecteur);
router.use("/", geoRouterSecteur);
router.use("/", geoRouterVillage);
router.use("/", inviteRouter);
export default router;
